[package]
name = "ffrm"
version = "0.1.0"
edition = "2021"
description = "查看谁占用了本地文件，解除占用，并删除文件"
license = "MIT"
repository = "https://github.com/gaoyia/ffrm"
homepage = "https://gaoyia.github.io/ffrm/"
readme = "README.md"
build = "build.rs"
exclude = [".github/", "site/"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
gpui = "0.2.2"
raw-window-handle = "0.6"
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_RestartManager",
    "Win32_System_Registry",
    "Win32_Networking_WinHttp",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
winresource = "0.1"
